<a href="https://colab.research.google.com/github/NiharikaKomaragiri/Python-Course-Work/blob/main/Copy_of_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
# Example: Product Prices
product_prices = pd.Series(
[2999, 15999, 52999, 4999, 1999],
index=["Wireless Earbuds", "Smartphone", "Laptop",
"Smartwatch", "Bluetooth Speaker"]
)
print(product_prices)

Wireless Earbuds      2999
Smartphone           15999
Laptop               52999
Smartwatch            4999
Bluetooth Speaker     1999
dtype: int64

In [ ]:
print("Mean",product_prices.mean())

Mean 15799.0

In [ ]:
print("Sum",product_prices.sum())

Sum 78995

In [ ]:
print("Max",product_prices.max())

Max 52999

In [ ]:
print("Min",product_prices.min())

Min 1999

In [ ]:
print("Head(First 3 Elements):\n",product_prices.head(3))

Head(First 3 Elements):
 Wireless Earbuds     2999
Smartphone          15999
Laptop              52999
dtype: int64

In [ ]:
print("Tail(Last 2 Elements):\n",product_prices.tail(2))

Tail(Last 2 Elements):
 Smartwatch           4999
Bluetooth Speaker    1999
dtype: int64

In [ ]:
print("Apply(Adding 18% GST):\n",product_prices.apply(lambda x:f'{x * 1.18}'))

Apply(Adding 18% GST):
 Wireless Earbuds     3538.8199999999997
Smartphone                     18878.82
Laptop                         62538.82
Smartwatch                      5898.82
Bluetooth Speaker    2358.8199999999997
dtype: object

In [ ]:
print('Map(Formating as currency):\n',product_prices.map(lambda x:f'₹{x}') )

Map(Formating as currency):
 Wireless Earbuds      ₹2999
Smartphone           ₹15999
Laptop               ₹52999
Smartwatch            ₹4999
Bluetooth Speaker     ₹1999
dtype: object

In [ ]:
print("Sort by values:\n",product_prices.sort_values())

Sort by values:
 Bluetooth Speaker     1999
Wireless Earbuds      2999
Smartwatch            4999
Smartphone           15999
Laptop               52999
dtype: int64

In [ ]:
print("Sort by Index:\n",product_prices.sort_index())

Sort by Index:
 Bluetooth Speaker     1999
Laptop               52999
Smartphone           15999
Smartwatch            4999
Wireless Earbuds      2999
dtype: int64

In [ ]:
print(product_prices.sort_index(ascending=False))

Wireless Earbuds      2999
Smartwatch            4999
Smartphone           15999
Laptop               52999
Bluetooth Speaker     1999
dtype: int64

In [ ]:
print("Value Counts:\n",product_prices.value_counts())

Value Counts:
 2999     1
15999    1
52999    1
4999     1
1999     1
Name: count, dtype: int64

In [ ]:
# Example: Product Details
data = {
"Product": ["Wireless Earbuds", "Smartphone", "Laptop",
"Smartwatch", "Bluetooth Speaker"],
"Brand": ["SoundMax", "TechNova", "ByteCore", "TimeTrack",
"EchoBoom"],
"Price": [2999, 15999, 52999, 4999, 1999],
"Stock": [50, 30, 20, 40, 60],
"BestSeller": [True, False, True, True, False]
}
df = pd.DataFrame(data)
print(df)

             Product      Brand  Price  Stock  BestSeller
0   Wireless Earbuds   SoundMax   2999     50        True
1         Smartphone   TechNova  15999     30       False
2             Laptop   ByteCore  52999     20        True
3         Smartwatch  TimeTrack   4999     40        True
4  Bluetooth Speaker   EchoBoom   1999     60       False

In [ ]:
print("Shape of DataFrame:",df.shape)

Shape of DataFrame: (5, 5)

In [ ]:
print("Columns in DataFrame:",df.columns)

Columns in DataFrame: Index(['Product', 'Brand', 'Price', 'Stock', 'BestSeller'], dtype='object')

In [ ]:
print("DataFrame INFO:")
print(df.info())

DataFrame INFO:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Product     5 non-null      object
 1   Brand       5 non-null      object
 2   Price       5 non-null      int64
 3   Stock       5 non-null      int64
 4   BestSeller  5 non-null      bool
dtypes: bool(1), int64(2), object(2)
memory usage: 297.0+ bytes
None

In [ ]:
df.head(3)

            Product     Brand  Price  Stock  BestSeller
0  Wireless Earbuds  SoundMax   2999     50        True
1        Smartphone  TechNova  15999     30       False
2            Laptop  ByteCore  52999     20        True

In [ ]:
df.tail(2)

             Product      Brand  Price  Stock  BestSeller
3         Smartwatch  TimeTrack   4999     40        True
4  Bluetooth Speaker   EchoBoom   1999     60       False

In [ ]:
print(df)
print(df.loc[1,"Product"])
print(df.loc[2,"Brand"])
print(df.loc[1,"Stock"])

print(df.iloc[4,0])
print(df.iloc[2,1])
print(df.iloc[3,3])

             Product      Brand  Price  Stock  BestSeller
0   Wireless Earbuds   SoundMax   2999     50        True
1         Smartphone   TechNova  15999     30       False
2             Laptop   ByteCore  52999     20        True
3         Smartwatch  TimeTrack   4999     40        True
4  Bluetooth Speaker   EchoBoom   1999     60       False
Smartphone
ByteCore
30
Bluetooth Speaker
ByteCore
40

In [ ]:
df.iloc[3]

Product       Smartwatch
Brand          TimeTrack
Price               4999
Stock                 40
BestSeller          True
Name: 3, dtype: object

In [ ]:
print(df)
df.loc[df['BestSeller']==True]
df.loc[df['Stock']<40]
df.loc[df['Price']<10000]

             Product      Brand  Price  Stock  BestSeller
0   Wireless Earbuds   SoundMax   2999     50        True
1         Smartphone   TechNova  15999     30       False
2             Laptop   ByteCore  52999     20        True
3         Smartwatch  TimeTrack   4999     40        True
4  Bluetooth Speaker   EchoBoom   1999     60       False

             Product      Brand  Price  Stock  BestSeller
0   Wireless Earbuds   SoundMax   2999     50        True
3         Smartwatch  TimeTrack   4999     40        True
4  Bluetooth Speaker   EchoBoom   1999     60       False

In [ ]:
print(df)
df.drop(columns=["Stock"])
#df.drop(columns=["Stock"],inplace=True) - Delete it permentaly

             Product      Brand  Price  Stock  BestSeller
0   Wireless Earbuds   SoundMax   2999     50        True
1         Smartphone   TechNova  15999     30       False
2             Laptop   ByteCore  52999     20        True
3         Smartwatch  TimeTrack   4999     40        True
4  Bluetooth Speaker   EchoBoom   1999     60       False

             Product      Brand  Price  BestSeller
0   Wireless Earbuds   SoundMax   2999        True
1         Smartphone   TechNova  15999       False
2             Laptop   ByteCore  52999        True
3         Smartwatch  TimeTrack   4999        True
4  Bluetooth Speaker   EchoBoom   1999       False

In [ ]:
df.rename(columns={"Brand":"Manufacture"})
#Rename temporary if you want permenent use inplace

             Product Manufacture  Price  Stock  BestSeller
0   Wireless Earbuds    SoundMax   2999     50        True
1         Smartphone    TechNova  15999     30       False
2             Laptop    ByteCore  52999     20        True
3         Smartwatch   TimeTrack   4999     40        True
4  Bluetooth Speaker    EchoBoom   1999     60       False

In [ ]:
print(df)
df.groupby("Brand").agg({"Price":"sum","Stock":"sum"})

             Product      Brand  Price  Stock  BestSeller
0   Wireless Earbuds   SoundMax   2999     50        True
1         Smartphone   TechNova  15999     30       False
2             Laptop   ByteCore  52999     20        True
3         Smartwatch  TimeTrack   4999     40        True
4  Bluetooth Speaker   EchoBoom   1999     60       False

           Price  Stock
Brand
ByteCore   52999     20
EchoBoom    1999     60
SoundMax    2999     50
TechNova   15999     30
TimeTrack   4999     40

In [ ]:
data2={
    "Brand":["SoundMax","TechNova","ByteCore","TimeTrack","EchoBoom"],
    "Rating":[4.2,4.5,4.0,4.3,3.9],
    "Discount":[28,40,16,10,5]
}
df_ratings=pd.DataFrame(data2)
print(df_ratings)

       Brand  Rating  Discount
0   SoundMax     4.2        28
1   TechNova     4.5        40
2   ByteCore     4.0        16
3  TimeTrack     4.3        10
4   EchoBoom     3.9         5

In [ ]:
df.merge(df_ratings,on="Brand")

             Product      Brand  Price  Stock  BestSeller  Rating  Discount
0   Wireless Earbuds   SoundMax   2999     50        True     4.2        28
1         Smartphone   TechNova  15999     30       False     4.5        40
2             Laptop   ByteCore  52999     20        True     4.0        16
3         Smartwatch  TimeTrack   4999     40        True     4.3        10
4  Bluetooth Speaker   EchoBoom   1999     60       False     3.9         5

In [ ]:
new_data={
    "Product":["Tablet"],
    "Brand":["SmartWare"],
    "price":[12999],
    "Stock":[25],
    "BestSeller":[False]
}
new_df=pd.DataFrame(new_data)
print(new_df)

  Product      Brand  price  Stock  BestSeller
0  Tablet  SmartWare  12999     25       False

In [ ]:
pd.concat([df,new_df],ignore_index=True)

             Product      Brand    Price  Stock  BestSeller    price
0   Wireless Earbuds   SoundMax   2999.0     50        True      NaN
1         Smartphone   TechNova  15999.0     30       False      NaN
2             Laptop   ByteCore  52999.0     20        True      NaN
3         Smartwatch  TimeTrack   4999.0     40        True      NaN
4  Bluetooth Speaker   EchoBoom   1999.0     60       False      NaN
5             Tablet  SmartWare      NaN     25       False  12999.0

In [ ]:
df.sort_values(by="Price", ascending=False)
df["Rank"] = df["Price"].rank(ascending=False)

In [ ]:
df.pivot_table(values="Price", index="Brand", columns="Stock",
aggfunc="mean")

Stock           20       30      40      50      60
Brand
ByteCore   52999.0      NaN     NaN     NaN     NaN
EchoBoom       NaN      NaN     NaN     NaN  1999.0
SoundMax       NaN      NaN     NaN  2999.0     NaN
TechNova       NaN  15999.0     NaN     NaN     NaN
TimeTrack      NaN      NaN  4999.0     NaN     NaN

In [ ]:
pd.crosstab(df["Brand"], df["Stock"])

Stock      20  30  40  50  60
Brand
ByteCore    1   0   0   0   0
EchoBoom    0   0   0   0   1
SoundMax    0   0   0   1   0
TechNova    0   1   0   0   0
TimeTrack   0   0   1   0   0